name: pepuch.github.io
description: my personal notes about programming
meta_description: "pepuch.github.io, my personal notes"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://pepuch.github.io'
google_analytics: 'UA-91032975-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://pepuch.github.io'
